# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: baec593626a3d36104c001a18589264e93dbbead6164342090fd8eb987b08eff914b4a899308f3489b6e2febceb989cbf04ba64119b6dfef29753aef8e706b1c

test:
  secret_key_base: d40da3a184b7badc4f2f9a45162288675c94b782ee53c6c54d6dc3aa69fb00f9269547b05cf54d68c097e58a2e7d0cd19ff6724c2e92e4433599927ba0ab129d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
